# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Lå°æ‚ çš„æ—¥å¸¸L
subtitle: "obsidianlyg"
description: "æœ€å¥½çš„ç”Ÿæ´»æ˜¯ï¼šæ—¶å…‰ï¼Œæµ“æ·¡ç›¸å®œï¼Œäººå¿ƒï¼Œè¿œè¿‘ç›¸å®‰"
keywords:
author: obsidianlyg
language: zh-CN
timezone: "Asia/Shanghai"

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
#url: https://obsidianlyg.gitee.io
#root: /

# url: https://obsisianlyg.top/
# root: /

url: https://obsidianlyg.github.io
root: /

# permalink: :year/:month/:day/:title/
permalink: :title/
# permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
# highlight:
#   enable: true
#   line_number: true
#   auto_detect: false
#   tab_replace: ''
#   wrap: true
#   hljs: false
# prismjs:
#   enable: true
#   preprocess: true
#   line_number: true
#   tab_replace: ''
highlight:
  enable: false # edit for Theme.shoka
  # line_number: true
  # auto_detect: true
  # tab_replace: ''
prismjs:
  enable: false # edit for Theme.shoka

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
# default_category: uncategorized
category_map:
  è®¡ç®—æœºç§‘å­¦: computer-science
  ä¸»é¢˜ä½œè€…çš„æ•™ç¨‹é…ç½®: note
  MongoDB: mongo
  Theme Shoka Documentation: theme-shoka-doc
  ä½¿ç”¨æµ‹è¯•: usetest
  å›¾åºŠçš„æµ‹è¯•: test-img
  markdownæµ‹è¯•: mktest
# tag_map:
# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: shoka

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: shoka

# Reward (Donate)
reward:
  # If true, reward will be displayed in every article by default.
  enable: true
  account:
    wechatpay: /wechatpay.png
    # alipay: /alipay.png
    # paypal: /paypal.png

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
# http://obsisianlyg.top:23000/obsidian/blog.git
deploy:
  type: git # typeä¸ºgit
  repo: https://github.com/obsidianlyg/obsidianlyg.github.io # ä»“åº“çš„URL

# edit for Theme.shoka
autoprefixer:
  exclude:
    - "*.min.css"

markdown:
  render: # æ¸²æŸ“å™¨è®¾ç½®
    html: false # è¿‡æ»¤ HTML æ ‡ç­¾
    xhtmlOut: true # ä½¿ç”¨ '/' æ¥é—­åˆå•æ ‡ç­¾ ï¼ˆæ¯”å¦‚ <br />ï¼‰ã€‚
    breaks: true # è½¬æ¢æ®µè½é‡Œçš„ '\n' åˆ° <br>ã€‚
    linkify: true # å°†ç±»ä¼¼ URL çš„æ–‡æœ¬è‡ªåŠ¨è½¬æ¢ä¸ºé“¾æ¥ã€‚
    typographer:
    quotes: "â€œâ€â€˜â€™"
  plugins: # markdown-itæ’ä»¶è®¾ç½®
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # æ–‡ç« ç›®å½•ä»¥åŠé”šç‚¹åº”ç”¨çš„classåç§°ï¼Œshokaä¸»é¢˜å¿…é¡»è®¾ç½®æˆè¿™æ ·
          tocClassName: "toc"
          anchorClassName: "anchor"
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "ä½ çŸ¥é“å¾—å¤ªå¤šäº†"

minify:
  html:
    enable: true
    stamp: false
    exclude:
      - "**/json.ejs"
      - "**/atom.ejs"
      - "**/rss.ejs"
  css:
    enable: true
    stamp: false
    exclude:
      - "**/*.min.css"
  js:
    enable: true
    stamp: false
    mangle:
      toplevel: true
    output:
    compress:
    exclude:
      - "**/*.min.js"

algolia:
  appId: GU3C7I5JLE
  apiKey: 594123984ffdf6366638b6ac80ae4c59
  adminApiKey: f9a47d17a5e4b51cd797fbf396e94e97
  chunkSize: 5000
  indexName: title
  fields:
    - title #å¿…é¡»é…ç½®
    - path #å¿…é¡»é…ç½®
    - categories #æ¨èé…ç½®
    - content:strip:truncate,0,4000
    - gallery
    - photos
    - tags

feed:
  limit: 20
  order_by: "-date"
  tag_dir: false
  category_dir: false
  rss:
    enable: true
    template: "themes/shoka/layout/_alternate/rss.ejs"
    output: "rss.xml"
  atom:
    enable: true
    template: "themes/shoka/layout/_alternate/atom.ejs"
    output: "atom.xml"
  jsonFeed:
    enable: true
    template: "themes/shoka/layout/_alternate/json.ejs"
    output: "feed.json"

## å“”å“”åŠŸèƒ½é…ç½®
## å…³æ³¨å…¬ä¼—å· "é»‘çŸ³å“”å“”"ï¼Œå‘é€: //bindCurrentUser:ä½ çš„APPID,ä½ çš„MASTERKEY,ä½ çš„RESTAPI
## å¯ç”¨leancloudå›½é™…ç‰ˆï¼Œå›½é™…ç‰ˆapiä¸º https://appidå‰å…«ä½.api.lncldglobal.com
bb:
  title: å“”å“” #é¡µé¢title
  permalink: https://obsidianlyg.gitee.io/bb/
  appId: QAgAM38qkcsPz8ziHqhJTfaY-gzGzoHsz
  appKey: a9Er9gvAvkF6AEJyfJyycODn
  serverURLs: https://qagam38q.lc-cn-n1-shared.com #ä½ çš„apiåœ°å€
  #  serverURLs: ['https://cdn.jsdelivr.net/gh/line/Bilibilis@latest','https://cdn.jsdelivr.net/gh/line/tieba@latest','https://cdn.jsdelivr.net/gh/line/twemoji@latest','https://cdn.jsdelivr.net/gh/line/weibo@latest']
  #  el: true
  limit: 10 #æ˜¾ç¤ºæ¡æ•°
  path: bb #è·¯å¾„åç§° ä¾‹å¦‚ï¼šhttps://ä½ çš„åŸŸå/bb
  content: "ğŸ‘‰ğŸ¼æ­¤è¯´è¯´é€šè¿‡ğŸ“±æ‰‹æœºå¾®ä¿¡å‘å‡ºï¼Œä¸»è¦è®°å½•é»‘çŸ³ç¢ç‰‡åŒ–æ€è€ƒå’ŒåŠ¨æ€ã€‚ğŸ“‘(è‹¥æœªæ­£ç¡®æ˜¾ç¤ºï¼Œå¯ä»¥æ‰‹åŠ¨åˆ·æ–°)" #æ˜¾ç¤ºåœ¨å“”å“”ä¸Šæ–¹,å¦‚ä¸éœ€è¦æ³¨é‡Šå³å¯

